### PR TITLE
Allow for full customization of the steps (boo#1134575)

### PR DESCRIPTION
**Pull request by hellcp**

### CODE REVIEW

**Comment by shundhammer** [comment]
I understand that column stretch was meant to have some margin to the left of the wizard steps:

wizard2

Where column #0 was always left empty, but it was as wide as column #1 which normally contains one of the icons: The green check mark or the white arrow.

I don't know why it was done that way and not just with a widget margin (AFAICS the last one to touch this was Coolo with the Qt4 migration 12 years ago).

If we no longer have that margin this way, we'll have to make sure to adapt the QSS style sheets accordingly; but that's alright IMHO because we don't use the wizard anywhere in situations where we don't have a QSS; at least, AFAIK.

**Comment by shundhammer** [comment]
Having said that, LGTM. Maybe @lslezak wants to add anything here?

**Comment by shundhammer** [comment]
@hellcp just mentioned on IRC that we have one place where this might be a problem: The one-click installer.

We might want to make sure that it also uses a QSS; it would be a visual improvement anyway.

**Comment by lslezak** [comment]
I'm not an Qt or QSS expert but the change looks reasonable to me. If it works I'm fine with that.

**Pull request merged**
