### PR TITLE
Fix compile with Qt 5.7

### PR DESCRIPTION
**Pull request by shumski**
[bsc#1001141](https://bugzilla.suse.com/show_bug.cgi?id=1001141)

### CODE REVIEW

**Comment by mvidner** [comment]
Thanks! I have created a Bugzilla ticket for this so that we can include the fix in SLE too.

**Comment by shundhammer** [comment]
LGTM

**Comment by shundhammer** [comment]
Background: When not-that-important Qt classes might become binary incompatible because they are not PIMPL'ed and they need some more data members, they introduce a new one like that QStyleOptionProgressBarV2, so newer code can use that one with the added data member, while old code remains working with the unchanged class, and they deprecate V2, V3 etc. so they can use it again.

That ...V2 here probably goes back to Qt4.

**Comment by mvidner** [comment]
A fixup was needed because we keep the version number in 3 places: https://github.com/libyui/libyui-qt/commit/a60ca09d8e68015ea482337365b3be3809ad5f45

**Pull request merged**
