### PR TITLE
Fix translations loading

### PR DESCRIPTION
**Pull request by imobachgs**
This patch fixes Qt translations. Although it works for several locales (`es_ES`, `de_DE`, `cs_CZ`, `fr_FR`, ...), it does not work for me in some situations (like `hu_HU`) although translations are successfully loaded. But, to be honest, this [Qt example](https://doc.qt.io/qt-5/qtwidgets-dialogs-standarddialogs-example.html) did not work either.

unexpected-click-spanish

### CODE REVIEW

**Comment by shundhammer** [comment]
LGTM.

Just be aware that this will still not cover all languages. On my system (latest Tumbleweed), I get those in `/usr/share/qt5/translations`:

- qtbase_bg.qm
- qtbase_ca.qm
- qtbase_cs.qm
- qtbase_da.qm
- qtbase_de.qm
- qtbase_en.qm
- qtbase_es.qm
- qtbase_fi.qm
- qtbase_fr.qm
- qtbase_gd.qm
- qtbase_he.qm
- qtbase_hu.qm
- qtbase_it.qm
- qtbase_ja.qm
- qtbase_ko.qm
- qtbase_lv.qm
- qtbase_pl.qm
- qtbase_ru.qm
- qtbase_sk.qm
- qtbase_uk.qm

**Comment by imobachgs** [comment]
I've found out that this patch won't be enough (as we are still loading `qt_` instead of `qtbase_`).

**Comment by imobachgs** [comment]
The patch fixes the translations loading but, for some reason, it does not seem to work for `hu_HU` in my system -I must be missing some package-, although it works just fine for `es_ES` or `de_DE`.

On the other hand, it looks like [QTranslator](https://doc.qt.io/qt-5/qtranslator.html#load) is smart enough to determine the file to load (it tries different alternatives, like `qt_de_DE.qm`, `qt_de_DE`, `qt_de`, etc.). So perhaps our fallback handling code is not needed anymore.

**Comment by shundhammer** [comment]
LGTM

**Pull request merged**
