### PR TITLE
Request the focus if yast is running fullscreen

### PR DESCRIPTION
**Pull request by antlarr**
Actively request the focus instead of relying on the windows manager
focus policy (and focus issues). This fixes bsc#974627: yast
not having the focus when run with Qt 5.6 under icewm (as in the
installation images).

### CODE REVIEW

**Comment by lslezak** [comment]
Please, update the patch version in `VERSION.cmake` and `package/libyui-qt.spec` add a new entry in `package/libyui-qt.changes` file.

Othewise it looks good! Thank you! :+1:

**Comment by lslezak** [comment]
LGTM, thanks a lot!

**Comment by sysrich** [comment]
:+1: Soo many SLE and TW issues we see in openQA will be smited by this commit - please make sure it ends up in both codebases as fast as sensibly possible :)

**Comment by lslezak** [comment]
Autosubmitted to SP2: https://ci.suse.de/view/libyui/job/libyui-qt-SLE-12/10/console:
```
yes | osc -A 'https://api.suse.de/' submitreq --no-cleanup 'Devel:YaST:Head' 'libyui-qt' 'SUSE:SLE-12-SP2:GA' -m 'submit new version 2.46.23' --yes
created request id 114577
```

For Factory TW I need to submit manually, the https://ci.opensuse.org/computer/yast-yui/load-statistics worker is down :worried:

**Pull request merged**
