### PR TITLE
Fix right to left mode for fa (boo#1156437)

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by lnussel** [comment]
please handle the packaging magic yourself. The spec file says I need to use rake whatever. I don't have a development environment for that. Verified the patch works by manually applying it to the package.

**Comment by Vogtinator** [comment]
This could just use `QLocale(lang).textDirection()` instead

**Comment by shundhammer** [comment]
Already fixed with another PR.

**Comment by Vogtinator** [comment]
> Fixed in PR #121.

Without

> This could just use `QLocale(lang).textDirection()` instead

though

**Comment by shundhammer** [comment]
https://bugzilla.suse.com/show_bug.cgi?id=1156437#c2

> That sounds like a good idea, but I don't know if we can rely on the Qt locale being set up correctly at that point in time already; in particular during installation when the user can change it on the fly in the first workflow step.
>
> I remember back when we introduced that layout direction support, for Qt it depended on the translations for Qt's predefined dialogs to be there; that was one that indicated the writing and layout direction. But they were not reliably there (or not for all the languages that we needed), so that tended to fail quite frequently.
>
> Also, I am not that sure if Farsi uses QLocale::ArabicScript in the context of Qt; I can't see anything that sounds like "FarsiScript" there:
>
>  https://github.com/qt/qtbase/blob/dev/src/corelib/text/qlocale.cpp#L3105
>
> For now, I'll simply extend the existing list; that I can do in 5 minutes. 
>
> The other thing would require me to do the whole testing cycle with a custom-built inst-sys which takes the better part of a working day and half a year worth of life energy. ;-(

**Comment by Vogtinator** [comment]
Just gave it a try:

```
        qDebug() << QLocale("de").textDirection();
        qDebug() << QLocale("ar").textDirection();
        qDebug() << QLocale("he").textDirection();
        qDebug() << QLocale("fa").textDirection();
```

outputs:

```
Qt::LeftToRight
Qt::RightToLeft
Qt::RightToLeft
Qt::RightToLeft
```

It does not use the current thread's locale, it uses whatever is given as argument, so the time of calling shouldn't matter.

**Pull request closed without merging**
