### PR TITLE
UI designer fix - show new widgets

### PR DESCRIPTION
**Pull request by lslezak**
Make the newly added widgets visible if adding to an already visible parent.

## Before Fix

A newly added widget (a PushButton in this case) is not visible, the needed space for the widget is added to dialog but the widget itself remains hidden:

ui_designer_before_qt_fix

## With the Fix

After the fix the widget is visible after add it (sorry, partly hidden by the spy dialog) :

ui_designer_qt_fixed

### CODE REVIEW

**Comment by mvidner** [comment]
Hmm, my objection should not be surprising: why do this 28 times when the widgets have a common parent? Or have you tried it and was there a problem?

**Comment by lslezak** [comment]
Um, a cannot see the place where it could be shared. Each widget usually has a `Q<Parent>` and an `Y<Parent>`.

But the Qt widget itself is created in the widget constructor. And IIRC the base class constructors are called *before* the derived class constructor. I.e. the parents cannot access the child widget yet.

The problem is that we can set the visibility only after the Qt widget has been actually created.

The only possibility is to move the initialization from the `YQWidgetFactory` factory methods to the widget constructors. Then we could share the `inherit_visibility` method in the parent. But that would be 28 changes in 28 files, I cannot see any difference... (And I'd rather prefer 28 changes in a *single* file.)

Or did I overlook something? I'm not a C++ expert...

**Comment by mvidner** [comment]
@shundhammer can you advise here please? It feels wrong to take care of [`QWidget::visible`](http://doc.qt.io/qt-5/qwidget.html#visible-prop) in this way.

**Comment by lslezak** [comment]
Closing, this has been fixed in a far better way in https://github.com/libyui/libyui-qt/pull/57 (thanks to @shundhammer!)

**Pull request closed without merging**
